apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendstore-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trendstore
  template:
    metadata:
      labels:
        app: trendstore
    spec:
      containers:
      - name: trendstore-container
        image: rakesh7264/trendstore-app:latest
        ports:
        - containerPort: 3000
